version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    container_name: pgadminlite_postgres
    environment:
      POSTGRES_DB: pgadmin_lite_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
